### ISSUE TITLE
Issue connecting with SASL_PLAIN config

### ISSUE THREAD

**Issue by arajguha** [vdesabou/kafka-docker-playground#1050]
I am trying to send data  from producer (using a node/go client) running in localhost (running in the host machine outside docker container).

The default config part for listeners in SASL_PLAIN is the following.
```
KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:SASL_PLAINTEXT
KAFKA_LISTENERS: EXTERNAL://:9092
KAFKA_ADVERTISED_LISTENERS: EXTERNAL://broker:9092
KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
```
And the ports forwarded from the plaintext docker-compose file is as follows:
```
ports:
      - "9092:9092"
      - "29092:29092"
      - "10000:10000"
```

Not I am giving the broker config in my producer as `localhost:29092`. I am unable to connect to the broker with that config. So, I tried changing the config in SASL_PLAIN to the below one:

```
KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:SASL_PLAINTEXT, SASL_PLAINTEXT:SASL_PLAINTEXT
KAFKA_LISTENERS: EXTERNAL://broker:9092,SASL_PLAINTEXT://localhost:29092
KAFKA_ADVERTISED_LISTENERS: EXTERNAL://broker:9092,SASL_PLAINTEXT://localhost:29092
```

Still facing the same issue. Can anyone point out the area where the problem is occurring? The other default configs seem to be good enough for it work.

**Comment by vdesabou** [comment]
After commit https://github.com/vdesabou/kafka-docker-playground/commit/7e7c5fcea9799015d2a45e2997072cfde80c2988 it should work, can you confirm ?

**Comment by arajguha** [comment]
Yes! It is working now. Had one more question. Is there any `env` config for enabling `auto_create_topic` ? Thanks in advance.

**Comment by vdesabou** [comment]
`auto.create.topics.enable` is try by default.
The env variable is KAFKA_AUTO_CREATE_TOPICS_ENABLE` 

example:

```
KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
```
