### ISSUE TITLE
Unexpected Kafka request of type METADATA during SASL handshake - error with sasl-plain example

### ISSUE THREAD

**Issue by hegdemahendra** [vdesabou/kafka-docker-playground#1164]
Hello team,

I am trying to run below playground setup -
https://github.com/vdesabou/kafka-docker-playground/tree/master/environment/sasl-plain

I need to produce the message from different machine so just added one more listener with name 'NIFI' (below section shows the additional commands added):

 KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:SASL_PLAINTEXT,HOST:SASL_PLAINTEXT**,NIFI:SASL_PLAINTEXT**
            KAFKA_LISTENERS: EXTERNAL://:9092,HOST://:29092,**NIFI://:9093**
            KAFKA_ADVERTISED_LISTENERS: EXTERNAL://broker:9092,HOST://localhost:29092,**NIFI://10.0.1.207:9093**
            KAFKA_LISTENER_NAME_EXTERNAL_SASL_ENABLED_MECHANISMS: PLAIN
            KAFKA_LISTENER_NAME_EXTERNAL_PLAIN_SASL_JAAS_CONFIG: |
                    org.apache.kafka.common.security.plain.PlainLoginModule required \
                    username="broker" \
                    password="broker" \
                    user_broker="broker" \
                    user_controlcenter="controlcenter-secret" \
                    user_schemaregistry="schemaregistry-secret" \
                    user_ksqldb="ksqldb-secret" \
                    user_connect="connect-secret" \
                    user_sftp="sftp-secret" \
                    user_client="client-secret";
            **KAFKA_LISTENER_NAME_NIFI_SASL_ENABLED_MECHANISMS: PLAIN
            KAFKA_LISTENER_NAME_NIFI_PLAIN_SASL_JAAS_CONFIG: |
                    org.apache.kafka.common.security.plain.PlainLoginModule required \
                    username="broker" \
                    password="broker" \
                    user_broker="broker" \
                    user_controlcenter="controlcenter-secret" \
                    user_schemaregistry="schemaregistry-secret" \
                    user_ksqldb="ksqldb-secret" \
                    user_connect="connect-secret" \
                    user_sftp="sftp-secret" \
                    user_client="client-secret";**

When I try to run the setup it continually started giving below error in kafka log :
 
[2021-07-05 06:36:08,903] INFO [SocketServer listenerType=ZK_BROKER, nodeId=1] Failed authentication with /10.0.1.228 (errorMessage=Unexpected Kafka request of type METADATA during SASL handshake.) (org.apache.kafka.common.network.Selector)

Could you please help me to understand the issue and the fix ?

Thanks
Mahendra

**Comment by vdesabou** [comment]
`NIFI://10.0.1.207:9093`

I don't think you can do that.
There is already a listener on port `29092` that you can access from localhost and I think it should work from another host as well

**Comment by hegdemahendra** [comment]
@vdesabou  - Thanks a lot, as you said I am able to access it from outside through 29092.
Appreciate your quick response.
