### ISSUE TITLE
Add ElasticCloud example for ES Sink connector 

### ISSUE THREAD

**Issue by rrao714** [vdesabou/kafka-docker-playground#1265]
Add ElasticCloud example for ES Sink connector 
https://github.com/vdesabou/kafka-docker-playground/tree/master/connect/connect-elasticsearch-sink

**Comment by vdesabou** [comment]
@rrao714 I added an example here https://github.com/vdesabou/kafka-docker-playground/tree/master/connect/connect-elasticsearch-cloud-sink
