### ISSUE TITLE
Add Gitpod Prebuilds

### ISSUE THREAD

**Issue by chuck-confluent** [vdesabou/kafka-docker-playground#1271]
Yay for adding gitpod! Here are a couple of suggested improvements to the user experience using  [gitpod prebuilds](https://www.gitpod.io/docs/prebuilds#prebuilds):

- in the `before` part of the task, run the utils.sh script to set container image tags and then docker-compose pull some images
- run start.sh in the `command` part of the task rather than `init` so that it runs indefinitely on launch
- install necessary stuff like the confluent CLI to the workspace, again in the `before` part of the task. Imagine the workspace is the user's laptop. Put all the prerequisites on there.

Happy GitPoding!

**Comment by vdesabou** [comment]
Hey Chuck ! Thanks for the advices:

This is my current gitpod.yml:

```
tasks:
  - init: |
      cd environment/plaintext && ./start.sh; ./stop.sh
  - command: |
      echo "nothing to do"
ports:
  - port: 9021
    onOpen: open-browser

vscode:
  extensions:
    - ms-azuretools.vscode-docker
```

> in the before part of the task, run the utils.sh script to set container image tags and then docker-compose pull some images

So I'm starting the most common environment `plaintext` so that all main images are pulled (zookeeper, connect, broker etc..)

> run start.sh in the command part of the task rather than init so that it runs indefinitely on launch

I don't really want to start something because when the user connects, he will choose one test to run, and in any case, the existing processes will be stopped because I always stop existing containers before starting a test. It's different from the Kafka-tutorials use case I believe

> install necessary stuff like the confluent CLI to the workspace, again in the before part of the task. Imagine the workspace is the user's laptop. Put all the prerequisites on there.

The playground is made so that the only requirement is to have docker installed, for all other things I use docker images. So for example for az CLI, I'm using a docker image, etc..
There is one exception for this, it's `ccloud`, and I will add it.

Thanks !

**Comment by chuck-confluent** [comment]
Sweet!

What about prebuilds? With prebuilds, the `init` command will run in a prebuild when you commit to the main branch, and then a snapshot is made. That way, users can open a new workspace with the docker images already pulled. Here is a picture from the gitpod docs that I found useful: [https://www.gitpod.io/docs/config-start-tasks#prebuild-and-new-workspaces](https://www.gitpod.io/docs/config-start-tasks#prebuild-and-new-workspaces).

Adding prebuilds requires adding something like this to `.gitpod.yml`:

```yml
github:
  prebuilds:
    main: true
```

as well as installing the Gitpod app in GitHub (you might want to adjust permissions for the Gitpod app for security).

**Comment by chuck-confluent** [comment]
Looks like you already added the prebuild. I left a comment that I think anything you want to have only in the prebuild step needs to be in `init` rather than `before` (I was wrong earlier).

Thanks as always for your amazing work on stuff like this!

**Comment by chuck-confluent** [comment]
Btw I've never seen anything quite like how you use utils.sh to namespace CLI tools with docker (e.g. `az`, `jq`). That's pretty neat! It gives you a lot of control over the behavior of the playground to minimize dependency issues. Nice!

**Comment by chuck-confluent** [comment]
> So I'm starting the most common environment plaintext so that all main images are pulled (zookeeper, connect, broker etc..)

Could you do `docker-compose pull` instead? Or is there another reason to actually run the start and stop scripts?

**Comment by vdesabou** [comment]
Like this do you think ?

```xml
tasks:
  - name: Install ccloud CLI and run environment/plaintext to download main docker images
    init: |
      curl -L --http1.1 https://cnfl.io/ccloud-cli | sudo sh -s -- -b /usr/local/bin
      cd environment/plaintext && ./start.sh; ./stop.sh
```

Yes I can check for docker-compose pull instead

**Comment by chuck-confluent** [comment]
I would just change the start and stop to `docker-compose pull` if the purpose is just to pull the images.

Since you're doing prebuilds, it might be handy to just have a function to pull all docker images referenced in the repo. That might be more of a maintenance burden than you'd like, since you might add and subtract different images at any time.

**Comment by vdesabou** [comment]
Hey Chuck,

I think I have now Prebuild working following your advices.

I [tried](https://github.com/vdesabou/kafka-docker-playground/commit/7b98254b004e9e45f18fd916b81ec305695b617a) to download every single docker image in the Prebuild, but I think it is overkill and will be bad for UX as whenever there would be a push to the repo (and I do a lot !), it will execute Prebuild and if someone tries to use the workspace, he will get this:

![CleanShot 2021-09-09 at 13 27 45](https://user-images.githubusercontent.com/4061923/132684679-95190328-da0a-4bc3-9f63-a913726c5ffb.jpg)

Unless I'm missing something ?

**Comment by chuck-confluent** [comment]
totally reasonable! feel free to close this issue if you like where it's at
