### ISSUE TITLE
Broken link: schema registry instructions

### ISSUE THREAD

**Issue by JustBerkhout** [vdesabou/kafka-docker-playground#144]
in ccloud/ccloud-demo/README.md

> a. [Enable](http://docs.confluent.io/current/quickstart/cloud-quickstart.html#step-3-configure-sr-ccloud) Confluent Cloud Schema Registry prior to running the demo

doesn't link to instructions for enabling schema registry.

**Comment by vdesabou** [comment]
Thanks @JustBerkhout, fixed by 0ec3bd0
