### ISSUE TITLE
ssl_kerberos/start.sh  fails with broker2.key doesn't exist

### ISSUE THREAD

**Issue by l2trace** [vdesabou/kafka-docker-playground#158]
This line fails with a fresh run of ssL-kerberos 
https://github.com/vdesabou/kafka-docker-playground/blob/a5112d0e4f3fee4f5a4d67b3fa0c6fdf06f237dd/environment/ssl_kerberos/start.sh#L95

it looks like broker2.key doesn't exist.  Maybe switch that whole block with 

```
docker exec -i kdc bash -c 'chmod a+r /var/lib/secret/*.key'

```

**Comment by vdesabou** [comment]
Thanks for reporting the issue, it should be fixed with https://github.com/vdesabou/kafka-docker-playground/commit/6577bb804fb0db97788860778b6b724ac4470eaf
