### ISSUE TITLE
Demo is not running since ccloud config file switched to json

### ISSUE THREAD

**Issue by mcascallares** [vdesabou/kafka-docker-playground#171]
I tried to execute this demo with the last version of ccloud-cli (details below) and it does not work since the cli config file switch from `.ccloud/config` to `.ccloud/config.json`.

I tried renaming the check and still it does not work, I guess is not only the name but also the format. Any hint to make it work?

Thanks

Reproduction:
 ```
 ./start.sh SCHEMA_REGISTRY_CONFLUENT_CLOUD
  08:34:29 Using Confluent Platform version default tag 6.0.0, you can use other version by exporting TAG environment   variable, example export TAG=5.5.1
  You will be using Confluent Cloud config: user=mcascallaresfondevila+copstam@confluent.io, environment=gcp,   cluster=mcascallares-gcp-demo, api key=****
  Continue (y/n)?y
  08:35:03 ERROR: /home/matiascascallaresfondevila/.ccloud/config is not set
```

CCloud CLI:
```
  Version:     v1.21.1
  Git Ref:     bd62699
  Build Date:  2020-12-04T20:29:05Z
  Go Version:  go1.14.7 (linux/amd64)
  Development: false
```

**Comment by vdesabou** [comment]
No it is a file that you need to manually create and populate.
It follows the same pattern as confluentinc/examples

**Comment by mcascallares** [comment]
Understood, thanks for your reply @vdesabou
