### ISSUE TITLE
cdc-oracle12-pdb-table.sh doesn't bring ksqldb properly

### ISSUE THREAD

**Issue by NathanNam** [vdesabou/kafka-docker-playground#173]
docker exec -i ksqldb-cli ksql http://ksqldb-server:8088
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Dec 10, 2020 5:50:58 PM org.jline.utils.Log logr
WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)
ksqlDB, Copyright 2017-2020 Confluent Inc.

CLI v0.13.0, Server v<unknown> located at http://ksqldb-server:8088
Server Status: <unknown>

Having trouble? Type 'help' (case-insensitive) for a rundown of how things work!

*************************************ERROR**************************************
Remote server at http://ksqldb-server:8088 does not appear to be a valid KSQL
server. Please ensure that the URL provided is for an active KSQL server.

The server responded with the following error:
Error issuing GET to KSQL server. path:/info
Caused by: java.net.UnknownHostException: failed to resolve 'ksqldb-server'
	after 2 queries
Caused by: failed to resolve 'ksqldb-server' after 2 queries
********************************************************************************

ksql>

It seems the port is not open properly.
```
➜  connect-cdc-oracle12-source docker ps
CONTAINER ID        IMAGE                                             COMMAND                  CREATED             STATUS                      PORTS                              NAMES
a04e6c2fb408        confluentinc/cp-enterprise-control-center:6.0.0   "/etc/confluent/dock…"   10 minutes ago      Up 10 minutes               0.0.0.0:9021->9021/tcp             control-center
e3958bcd44ef        vdesabou/kafka-docker-playground-connect:6.0.0    "/etc/confluent/dock…"   10 minutes ago      Up 10 minutes               0.0.0.0:8083->8083/tcp, 9092/tcp   connect
770a4b9d6341        confluentinc/cp-schema-registry:6.0.0             "/etc/confluent/dock…"   10 minutes ago      Up 6 minutes                0.0.0.0:8081->8081/tcp             schema-registry
aee19c461a56        confluentinc/ksqldb-cli:latest                    "/bin/sh"                10 minutes ago      Up 10 minutes                                                  ksqldb-cli
65030f3f4023        confluentinc/cp-server:6.0.0                      "/etc/confluent/dock…"   10 minutes ago      Up 5 minutes                0.0.0.0:9092->9092/tcp             broker
f4778d5b2be9        oracle/database:12.2.0.1-ee                       "/bin/sh -c 'exec $O…"   10 minutes ago      Up 10 minutes (unhealthy)   0.0.0.0:1521->1521/tcp             oracle
68b1d5876a4e        confluentinc/cp-zookeeper:6.0.0                   "/etc/confluent/dock…"   10 minutes ago      Up 10 minutes               2181/tcp, 2888/tcp, 3888/tcp       zookeeper

**Comment by vdesabou** [comment]
Isn't it fixed by https://github.com/vdesabou/kafka-docker-playground/pull/174 ?

**Comment by NathanNam** [comment]
#174 has addressed the issue.
