### ISSUE TITLE
2way-ssl certs working from same machine only but not from other machine

### ISSUE THREAD

**Issue by hegdemahendra** [vdesabou/kafka-docker-playground#1739]
Hello Team,

This may not be an issue and just a question -
I am using https://github.com/vdesabou/kafka-docker-playground/blob/master/environment/2way-ssl
to setup broker with ssl.

It works well when kafka client is in same machine (I am using Apach Nifi to produce/consume messages)
But when I try to connect to broker from different machine in same network it is not working.

I added below DNS/IPs :
[alt_names]
DNS.1 = $i
DNS.2 = localhost
DNS.3 = ip-<my server ip>.ec2.internal
IP.1 = {my server ip}
IP.2 = 0.0.0.0

What could be the possible reason ?

I am using ip:port to access broker from another machine and not dns name.

Thanks
Mahendra

**Comment by vdesabou** [comment]
Hey @hegdemahendra 

This playground is made to be used 100% within Docker, so what you're trying to do is not supported.
In my examples, whenever I have a Java producer for example, I set it up within a container.
Sorry but I won't be able to help here

**Comment by hegdemahendra** [comment]
Thanks for your reply @vdesabou
