### ISSUE TITLE
docker-compose version 1.28.0 or greater is required. Current reported version: 1.24.0 

### ISSUE THREAD

**Issue by dreamer-kafka** [vdesabou/kafka-docker-playground#2128]
when i try to git clone this project in my google cloud shell.I am getting below error.I need to work on connectors.I was able to work perfectly fine last year(feb2021-nov2021) but from (dec 2021).I am getting these errors and not able to use this.kindly help me resolve this.

for your reference:
docker-compose version 1.28.0 or greater is required. Current reported version: 1.24.0  
Successfully built c0d12208ecce
Successfully tagged vdesabou/kafka-docker-playground-connect:7.0.1
06:58:09 ℹ️ 💫 Using 🔗connector: confluentinc/kafka-connect-jdbc:10.3.2 📅release date: 2022-02-05 🌐documentation: https://docs.confluent.io/kafka-connect-jdbc/current/
06:58:09 ℹ️ 🎓 To specify different version, check the documentation https://kafka-docker-playground.io/#/how-to-use?id=🔗-for-connectors
06:58:10 ℹ️ docker-compose version 1.28.0 or greater is required.  Current reported version: 1.24.0

xxxxxx@cloudshell:~/play/kafka-docker-playground/connect/connect-jdbc-postgresql-source (disco-bedrock-312706)$ docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES

**Comment by vdesabou** [comment]
You need to upgrade docker-compose as the error suggests.
The minimum requirement is due to https://github.com/vdesabou/kafka-docker-playground/issues/1039#issuecomment-853846001

**Comment by dreamer-kafka** [comment]
Any steps available to upgrade this docker-compose version from 1.24 to 1.28.....All i did is just git clone the project using below command and run the connect. 
1. git clone https://github.com/vdesabou/kafka-docker-playground.git
2. ./postgres-mtls.sh

**Comment by vdesabou** [comment]
https://docs.docker.com/compose/install/

It is out of scope of this repo, docker-compose is a 3rd party tool
