### ISSUE TITLE
connect/connect-teradata-sink

### ISSUE THREAD

**Issue by cdpop** [vdesabou/kafka-docker-playground#2153]
Adding request for having a teradata sink connector example.

**Comment by vdesabou** [comment]
Do you know how you will do it? There is no Docker image for teradata AFAIK, only a VM is available.

i was thinking using a GCP instance ( instructions are on the website there https://quickstarts.teradata.com/current/vantage.express.gcp.html)

but maybe there is other way?

**Comment by cdpop** [comment]
I'm doing some research and I found the following for the docker images:
https://quickstarts.teradata.com/jupyter.html#_teradata_jupyter_docker_image
_I think_ we can use this jupyter docker image:
https://quickstarts.teradata.com/jupyter.html#_teradata_jupyter_docker_image
My thought process was the user needs to go download/create the account and the load and setting tag can be done by the script. I think we have some instructions in other connectors where we ask the user to download the drivers. Think we should just do the GCP setup instead?

**Comment by vdesabou** [comment]
I'm closing this one. Jupiter docker image is something else. What we need is Vantage Express and it's only available as a VM..
