### ISSUE TITLE
Kerberos SASL_SSL can't create or consume topic

### ISSUE THREAD

**Issue by deshmukhrajvardhan** [vdesabou/kafka-docker-playground#2222]
Was unable to observe creation or consumption for messages of a topic via control centre GUI **or** the terminal when i run the
```
13:26:13 ℹ️ -----------------------------------------
13:26:13 ℹ️ Example configuration to access kafka:
13:26:13 ℹ️ -----------------------------------------
13:26:13 ℹ️ -> docker-compose exec client bash -c 'kinit -k -t /var/lib/secret/kafka-client.key kafka_producer && kafka-console-producer --broker-list broker:9092 --topic test --producer.config /etc/kafka/producer.properties'
13:26:13 ℹ️ -> docker-compose exec client bash -c 'kinit -k -t /var/lib/secret/kafka-client.key kafka_consumer && kafka-console-consumer --bootstrap-server broker:9092 --topic test --consumer.config /etc/kafka/consumer.properties --from-beginning'
```  

## Verified Plaintext setup
Was able to run external application that Produces and Consumes

## My main agenda
I'm trying to use external application with the kerberos setup.
I tried using client's properties file
https://github.com/vdesabou/kafka-docker-playground/blob/master/environment/ssl_kerberos/client/producer.properties
, but the library i use demands different configs.

https://github.com/edenhill/librdkafka/wiki/Using-SASL-with-librdkafka#5-configure-kafka-client-on-client-host

Would greatly appreciate you help! Thanks is advance

**Comment by vdesabou** [comment]
Hello, thanks for using this repo.

Unfortunately, I'm not able to support custom modifications. I simply have no time to do that.
I can only maintain existing examples.
