### ISSUE TITLE
Unable to access connectors

### ISSUE THREAD

**Issue by dreamer-kafka** [vdesabou/kafka-docker-playground#2530]
Getting below error when I try to run the connectors in Kafka-docker-playground
ERROR: /home/kafka-docker-playground/connect/connect-jdbc-oracle12-sink/linuxx64_12201_database.zip is missing. It must be downloaded manually in order to acknowledge user agreement

**Comment by vdesabou** [comment]
Yes that is explained in README:

Note: Oracle Database Enterprise Edition 12.x and 18c are no longer available for download. The software is available as a media or FTP request for those customers who own a valid Oracle Database product license for any edition. To request access to these releases, follow the instructions in [Oracle Support Document 1071023.1 (Requesting Physical Shipment or Download URL for Software Media)](https://support.oracle.com/epmos/faces/ui/km/DocumentDisplay.jspx?id=1071023.1) from My Oracle Support.
