### ISSUE TITLE
2way-ssl broker configurations missing the parameter `KAFKA_LISTENER_SECURITY_PROTOCOL_MAP`

### ISSUE THREAD

**Issue by anjinarra** [vdesabou/kafka-docker-playground#2771]
When multiple brokers are enabled, broker 2 and 3 fail with the SSL mapping errors. The following parameter needs to be configured:

KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: SSL:SSL

**Comment by vdesabou** [comment]
Thanks for reporting @anjinarra !
