### ISSUE TITLE
How to connect to Kafka cluster using Spring boot

### ISSUE THREAD

**Issue by nirmal-chg** [vdesabou/kafka-docker-playground#3026]
I am trying to use `environment/sasl-ssl/docker-compose.yml` but since it does not expose `localhost` as advertised listener I am not being able to connect to Kafka using Spring boot. Is there anyway to solve this issue.

**Comment by vdesabou** [comment]
This repo is meant to be used exclusively  within docker, that’s why I don’t want to expose advertisers. Plaintext is an exception but I personally don’t use that listener..
You can run your sprint boot app within a docker image for example, that’s how I run Java producers and consumers for example

**Comment by nirmal-chg** [comment]
In my case I have to debug and run in local mode so creating image for each change is not feasible. Since you wrote all this if you don't mind would you please give me insight to expose `localhost` and test it out.

**Comment by vdesabou** [comment]
Sorry I am not going to do that. This is not what for the repo is meant, it is no meant to run locally
