### ISSUE TITLE
playground container recreate doesn't take env variables into account 

### ISSUE THREAD

**Issue by cdpop** [vdesabou/kafka-docker-playground#4567]
When you run `playground container recreate` it does not take into account environment variables. So if you have JMX enabled, the agent doesn't get set on the container again:
Example:
      KAFKA_OPTS: -javaagent:/usr/share/jmx_exporter/jmx_prometheus_javaagent-0.12.0.jar=1234:/usr/share/jmx_exporter/kafka-connect.yml

**Comment by vdesabou** [comment]
@cdpop this should be fixed now, can you confirm ?
