### ISSUE TITLE
Connect container is not starting up in time

### ISSUE THREAD

**Issue by agentsim** [vdesabou/kafka-docker-playground#47]
When running `azure-data-lake-storage-gen2.sh`, the process fails to start Kafka Connect:

```
Creating kdc             ... done
Creating schema-registry ... done
Creating zookeeper       ... done
Creating client          ... done
Creating broker          ... done
Creating connect         ... done
Creating control-center  ... done
14:03:33 Waiting up to 480 seconds for Kafka Connect connect to start
ERROR: The logs in connect container do not show 'Finished starting connectors and tasks' after 480 seconds. Please troubleshoot with 'docker container ps' and 'docker container logs'.```

The `connect` container stops within about 20 seconds, but the logs do now show any errors or exceptions.

**Comment by vdesabou** [comment]
There is nothing specific to ADLS2 when we start the connect container here, so I assume you'll get the same error for every connector.
Can you attach the logs?
What gives `docker container ls -a` ? In order to see the STATUS from `connect`container

**Comment by vdesabou** [comment]
@agentsim This is probably a Docker memory issue, can you increase docker memory ? Default 2Gb is not enough, personally I use 10Gb:

![screenshot-20200825-151622](https://user-images.githubusercontent.com/4061923/91183423-bfee7400-e6eb-11ea-912a-dec2584dd4f7.jpg)

**Comment by agentsim** [comment]
Thanks, that did the trick.
