### ISSUE TITLE
blob sink connector

### ISSUE THREAD

**Issue by techsalopriyanshu** [vdesabou/kafka-docker-playground#5295]
Hello vdesabou , I am Priyanshu verma from India basically there is some big in the Azure Data Lake Storage Gen2 Sink Connector for Confluent Platform 

The bug is Related to Date format time , I want to solve this bug so for this purpose need a source code for this Connector 
Please see this Issue and Help me 

Contact me through priyanshu@techsalo.com

**Comment by vdesabou** [comment]
If you have a support contract with Confluent, raise a ticket, otherwise reach out to the community for help

**Comment by techsalopriyanshu** [comment]
No i dont have a support contract with confluent and that's why i reached
out to you for help like i want to know the source code is available for
the Azure Data Lake Storage Gen2 Sink Connector ?

**Comment by vdesabou** [comment]
No it's proprietary code

**Comment by techsalopriyanshu** [comment]
So, I want to know how can anybody Report this bug to confluent that this
is the bug we found with details and they reach out to us ?

**Comment by vdesabou** [comment]
you can use https://forum.confluent.io/

In this repo, you can only report issues with existing example. I'm not doing support for other issues.
