### ISSUE TITLE
Using plain and OAUTHBEARER

### ISSUE THREAD

**Issue by astream2018** [vdesabou/kafka-docker-playground#5827]
https://github.com/vdesabou/kafka-docker-playground/blob/986a70c3904ab1f540c50c5c4feec8b911b6aea9/ccloud/audit-log-connector/start.sh#L57

I'm running to an issue with the following error:

Failed to start task auditlogFileStream-0 (org.apache.kafka.connect.runtime.Worker:832)
org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
Caused by: org.apache.kafka.common.KafkaException: Failed to create new NetworkClient
Caused by: org.apache.kafka.common.KafkaException: java.lang.IllegalArgumentException: Unexpected SASL mechanism: PLAIN
Caused by: java.lang.IllegalArgumentException: Unexpected SASL mechanism: PLAIN

The Audit log Cluster is using sasl.mechanism PLAIN and the data cluster is OAUTHBEARER. The cluster properties are already configured to use OAUTHBEARER. When try to set both is gives an error 'Unexpected SASL mechanism: PLAIN'

**Comment by vdesabou** [comment]
are you running out of the box example ? If you have modified the example in any way, I cannot provide any support

**Comment by vdesabou** [comment]
closing as per my previous comment
