### ISSUE TITLE
License Replication Factor Must Be 3 - ccloud.schema-registry-security-plugin

### ISSUE THREAD

**Issue by feocco** [vdesabou/kafka-docker-playground#583]
Schema Registry container fails to start due to replication factor being 1. Need to increase this to 3 for demo to proceed:
* https://github.com/vdesabou/kafka-docker-playground/blob/fc5669db2788a6346faf33e72529a7d33551f126/ccloud/schema-registry-security-plugin/docker-compose.yml#L30

**Comment by vdesabou** [comment]
Thanks for reporting 👍
