### ISSUE TITLE
IBM Source Connector Missing JARS

### ISSUE THREAD

**Issue by feocco** [vdesabou/kafka-docker-playground#6]
Current instructions for IBM Source Connector say to simply run
`./ibm-mq.sh`

Doing this alone will net you a `java.lang.ClassNotFoundException: com.ibm.mq.jms.MQConnectionFactory` when creating connector

---

How I fixed. Download the JAR files from IBM:
* https://www-945.ibm.com/support/fixcentral/swg/selectFixes?product=ibm%2FWebSphere%2FWebSphere+MQ&fixids=9.0.0.4-IBM-MQ-Install-Java-All&source=dbluesearch&function=fixId&parent=ibm/WebSphere

Copy JAR files into IBM connect directory
`cp /Users/joe.feocco/Downloads/ibm/wmq/JavaSE /Users/joe.feocco/repos/kafka-docker-playground/connect/connect-ibm-mq-source/JavaSE`

Edit docker-compose volumes
```
    volumes:
        - ../../connect/connect-ibm-mq-source/JavaSE:/usr/share/confluent-hub-components/confluentinc-kafka-connect-ibmmq/lib/JavaSE
```

Then run `./ibm-mq.sh`

**Comment by vdesabou** [comment]
Thanks Joe for reporting this.
I've tried to improve the process in https://github.com/vdesabou/kafka-docker-playground/commit/c4f4c5eb0a49c51378e0854919b0a574a02e151f

FYI, I'm working on adding [Travis CI](https://travis-ci.org/vdesabou/kafka-docker-playground) so the repository should be more robust in a few days
