### ISSUE TITLE
UNKNOWN_TOPIC_OR_PARTITION - JDBC Source - SQL Server

### ISSUE THREAD

**Issue by feocco** [vdesabou/kafka-docker-playground#87]
The `..connect/connect-jdbc-sqlserver-source` example fails to produce to a topic since `auto.create.topics.enable` is set to `false` in the base Kafka image.

The connector only produces after manually creating the topic `sqlserver-customers`

**Comment by vdesabou** [comment]
Have you made custom modifications ? This test is running everyday in Travis with no problem
This test is using `cp-server` docker image, I don't think it has `auto.create.topics.enable=false`

**Comment by feocco** [comment]
Woops.... I didn't see my git markup in that file :). My apologies!
